subcategories = {
    "Ciencia y naturaleza": 3,
    "Historia y humanidades": 4,
    "Misterio y otras realidades": 5,
    "Fe, filosofía y espiritualidad": 8,
    "Polideportivo": 13,
    "Fútbol": 14,
    "Mundo y sociedad": 18,
    "Cine, tv y espectáculos": 19,
    "Viajes y lugares": 24,
    "Humor y entretenimiento": 27,
    "Política, economía y opinión": 31,
    "Negocios y sectores": 35,
    "Marketing y estrategia": 37,
    "Desarrollo personal": 38,
    "Hijos y educación": 39,
    "Mente y psicología": 40,
    "Salud, hogar y consumo": 41,
    "Arte y literatura": 43,
    "Videojuegos, rol y anime": 44,
    "Internet y tecnología": 45,
    "Aficiones y gastronomía": 48,
    "Pareja y relaciones": 49,
    "Idiomas": 51,
    "Magazine y variedades": 54,
    "Noticias y sucesos": 58,
    "Alternativa e indie": 62,
    "Blues y Jazz": 63,
    "Electrónica": 64,
    "Pop y Pop-Rock": 65,
    "Rock y Metal": 66,
    "BSO y Clásica": 67,
    "Hip Hop y Rap": 68,
    "Soul, Funk y R&amp;B": 70,
    "Músicas del mundo y otras": 71,
    "Experimental y new age": 72,
}
